// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: genom.proto
#ifndef GRPC_genom_2eproto__INCLUDED
#define GRPC_genom_2eproto__INCLUDED

#include "genom.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace GenomEvaluation {

class GenomEvaluation final {
 public:
  static constexpr char const* service_full_name() {
    return "GenomEvaluation.GenomEvaluation";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetIndividual(::grpc::ClientContext* context, const ::GenomEvaluation::Genom& request, ::GenomEvaluation::Individual* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GenomEvaluation::Individual>> AsyncGetIndividual(::grpc::ClientContext* context, const ::GenomEvaluation::Genom& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GenomEvaluation::Individual>>(AsyncGetIndividualRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GenomEvaluation::Individual>> PrepareAsyncGetIndividual(::grpc::ClientContext* context, const ::GenomEvaluation::Genom& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GenomEvaluation::Individual>>(PrepareAsyncGetIndividualRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GenomEvaluation::Individual>* AsyncGetIndividualRaw(::grpc::ClientContext* context, const ::GenomEvaluation::Genom& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GenomEvaluation::Individual>* PrepareAsyncGetIndividualRaw(::grpc::ClientContext* context, const ::GenomEvaluation::Genom& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetIndividual(::grpc::ClientContext* context, const ::GenomEvaluation::Genom& request, ::GenomEvaluation::Individual* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GenomEvaluation::Individual>> AsyncGetIndividual(::grpc::ClientContext* context, const ::GenomEvaluation::Genom& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GenomEvaluation::Individual>>(AsyncGetIndividualRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GenomEvaluation::Individual>> PrepareAsyncGetIndividual(::grpc::ClientContext* context, const ::GenomEvaluation::Genom& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GenomEvaluation::Individual>>(PrepareAsyncGetIndividualRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::GenomEvaluation::Individual>* AsyncGetIndividualRaw(::grpc::ClientContext* context, const ::GenomEvaluation::Genom& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GenomEvaluation::Individual>* PrepareAsyncGetIndividualRaw(::grpc::ClientContext* context, const ::GenomEvaluation::Genom& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetIndividual_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetIndividual(::grpc::ServerContext* context, const ::GenomEvaluation::Genom* request, ::GenomEvaluation::Individual* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetIndividual : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GetIndividual() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetIndividual() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetIndividual(::grpc::ServerContext* context, const ::GenomEvaluation::Genom* request, ::GenomEvaluation::Individual* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetIndividual(::grpc::ServerContext* context, ::GenomEvaluation::Genom* request, ::grpc::ServerAsyncResponseWriter< ::GenomEvaluation::Individual>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetIndividual<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_GetIndividual : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GetIndividual() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetIndividual() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetIndividual(::grpc::ServerContext* context, const ::GenomEvaluation::Genom* request, ::GenomEvaluation::Individual* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetIndividual : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_GetIndividual() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::GenomEvaluation::Genom, ::GenomEvaluation::Individual>(std::bind(&WithStreamedUnaryMethod_GetIndividual<BaseClass>::StreamedGetIndividual, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GetIndividual() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetIndividual(::grpc::ServerContext* context, const ::GenomEvaluation::Genom* request, ::GenomEvaluation::Individual* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetIndividual(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::GenomEvaluation::Genom,::GenomEvaluation::Individual>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetIndividual<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetIndividual<Service > StreamedService;
};

}  // namespace GenomEvaluation


#endif  // GRPC_genom_2eproto__INCLUDED
